version: '3'

services:
  jekyll_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: gabe_jekyll 
    container_name: my_jekyll 
    volumes:
      - ./code:/code
    network_mode: host
    entrypoint:
      - /bin/bash
      - start.sh